__tests__/virtual-lab/VirtualLabMemberIcon.spec.tsx
src/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(pages)/team/page.tsx
src/components/VirtualLab/CreateVirtualLabButton/MembersForm.tsx
src/components/VirtualLab/ProjectTeamTable/index.tsx
src/components/VirtualLab/VirtualLabHomePage/Member.tsx
src/components/VirtualLab/VirtualLabHomePage/VirtualLabUsers.tsx
src/components/VirtualLab/VirtualLabMemberIcon/index.tsx
src/components/VirtualLab/projects/ModalInviteProjectMember/Footer.tsx
src/components/VirtualLab/projects/ModalInviteProjectMember/InviteVlabMember.tsx
src/components/VirtualLab/projects/ModalInviteProjectMember/ModalInviteVlabMember.tsx
src/components/VirtualLab/projects/ModalInviteProjectMember/NewMember.tsx
src/components/VirtualLab/projects/ModalInviteProjectMember/hooks.ts
src/components/VirtualLab/projects/VirtualLabProjectHomePage/index.tsx
src/components/VirtualLab/projects/VirtualLabProjectList/NewProjectModalForm.tsx
src/components/VirtualLab/projects/VirtualLabProjectList/index.tsx
src/state/virtual-lab/lab.ts
src/state/virtual-lab/projects.ts

1. enabling the invites in both in virtual lab and project creation process
2. enabling the invites within virtual lab and project sections
3. Add two icons for invites (accepted/non-accepted) to distinguish for pending requests.
4. FIX: the invites within the virtual lab was relaying on the project endpoint.
5. FIX: vlab invite component and different styling
6. FIX: tests
**Note**:  the invites should be refactored/improved, due to urgency to deliver this ticket i will postpone it to a later moment.

re-enable invites both in vlab, project, in creation and within sections

---

.env
.env.development
.env.production
src/env.mjs

Now local dev server points to the staging environment.
Also, entries which are not common for all environments were moved out of .env, so that in deployments they have to be explicitly provided (otherwise the server will throw an error). This will prevent the leakage of wrong defaults.

Update dot env files

---

.env.development

Most of the services are available under `staging.openbraininstitute.org` domain except of nexus which is still available from `staging.openbluebrain.com`.

Reflect domain migration in .env.development

---

package-lock.json
package.json

This is a temporary solution.
It turns out there is a [bug in npm](https://github.com/npm/cli/issues/4828) that breaks sharp while used in multiple environments/architectures. Some more details: https://toolonline.net/en/CodeDocs/sharp/installation.
Maybe we should switch to using some npm alternative instead. Otherwise, after somebody updates the packages this thing might break as well.

Fix sharp not available in production builds

---

src/util/nexus.ts

The assumption that current nexus deployment domain will be always in the _self is not correct.
It turns out we have some entities with bbp.epfl.ch domain in our current staging nexus.
Current solution parses the url backwards, so the result doesn't depend on the domain.

Correctly parse nexus self urls

---

.github/workflows/publish-staging-image.yml

It turns out by accident I've removed id token permissions necessary to do aws auth.

Return back id token permissions for staging GitHub Action

---

src/components/VirtualLab/VirtualLabBanner/VirtualLabMainStatistics.tsx
src/components/VirtualLab/VirtualLabBanner/index.tsx
src/components/VirtualLab/projects/VirtualLabProjectHomePage/index.tsx
src/components/VirtualLab/projects/VirtualLabProjectList/VirtualLabProjectItem.tsx
src/state/virtual-lab/lab.ts

The current change:
* Removes current balance component which has number of usability issues.
* Adds rendering of the balance to VLab/Project details banner.
Before:
After:
Removed content is highlighted in red, added - in green.

Show real balances from API

---

src/components/LandingPage/LandingPage.module.css
src/components/LandingPage/LandingPage.tsx
src/components/LandingPage/components/SanityContentRTF/SanityContentParagraph/SanityContentParagraph.module.css
src/components/LandingPage/components/select-currency/select-currency.module.css
src/components/LandingPage/components/swipeable-cards-list/swipeable-cards-list.module.css
src/components/LandingPage/components/swipeable-cards-list/swipeable-cards-list.tsx
src/components/LandingPage/content/content.ts
src/components/LandingPage/content/news.ts
src/components/LandingPage/global.css
src/components/LandingPage/layout/Menu/PopupMenu/PopupMenu.tsx
src/components/LandingPage/sections/SectionNews/SectionNews.tsx
src/components/LandingPage/styles.module.css
src/components/LandingPage/styles.ts
src/components/LandingPage/utils.ts
src/components/LandingPage/widgets/FromCellToBrain/FromCellToBrain.module.css
src/components/LandingPage/widgets/FromCellToBrain/FromCellToBrain.tsx
src/components/LandingPage/widgets/News/NewsCard/NewsCard.tsx
src/components/LandingPage/widgets/PriceList/large-screen/FeatureBloc/FeatureLine/FeatureCell/FeatureCell.module.css
src/components/LandingPage/widgets/PriceList/large-screen/FeatureBloc/FeatureLine/FeatureCell/FeatureCell.tsx
src/components/LandingPage/widgets/PriceList/small-screen/small-screen.tsx

- (13) subcellular / cellular / circuit / .. grid : is not obvious we have other scale on mobile
- (6) The news list is too long. Add a More button
- (50) Currency combo goes behind the plans header.
- Bottom margin of 42 in paragraphs sections
- (51) on the desktop, we've lost the little (i) info button over the 'Partial build'.

Fourth round of fixes

---

src/components/Filter/CheckList/Description.tsx
src/components/build-section/virtual-lab/synaptome/molecules/SynapseSet.tsx
src/components/build-section/virtual-lab/synaptome/molecules/constants.ts
src/components/explore-section/ExploreSectionListingView/WithControlPanel.tsx
src/state/build-section/cell-types.ts

- fix missing values for etypes from nexus ([#14](https://github.com/openbraininstitute/prod-build-emodel/issues/14#issuecomment-2690536170))
- fix synapse configuration formula and target naming ([#11](https://github.com/openbraininstitute/prod-singlecell-simulation/issues/11#event-16510453628))

fix missing values from nexus

---

src/components/LandingPage/components/SanityContentRTF/SanityContentTitle/SanityContentTitle.tsx
src/components/LandingPage/components/SanityContentRTF/SanityContentTitle/special-widget.tsx
src/components/LandingPage/layout/Menu/Menu.tsx
src/components/LandingPage/styles.module.css

The temporary button to go to the coming-soon page can be added/removed in Sanity like this:
You just need to add a title H3 with this special title:
```
{{button}{/coming-soon}{Go to your lab}}
```
A button with two arguments:
- the link: `/coming-soon`
- the caption: `Go to your lab`

Go to your lab buttons

---

.deployment-envs/.env.staging
src/app/api/auth/new-access-token/route.ts
src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(secondary)/build/me-model/new/configure/page.tsx
src/auth.ts
src/components/build-section/virtual-lab/me-model/BluePyEModelContainer.tsx
src/components/build-section/virtual-lab/me-model/pending-validation-modal-hook.tsx
src/services/virtual-lab/build/me-model/bluepy-emodel.ts
src/services/virtual-lab/build/me-model/websocket.ts
src/services/ws-common.ts

These are mostly workarounds to make me-model validation work:
* Add websocket ping messages so that AWS ALB do not close the connection due to reaching inactivity threshold.
* Refresh access token before starting the validation - eventually this will have to be replaced by access token management in the service itself (separate KC client with token exchange capability and longer access token TTL).
* Set current API Gateway URL.

Make me-model validation more reliable

---

src/components/explore-section/ControlPanel/index.tsx

Fixes openbraininstitute/prod-build-emodel#13

Text below a 'Name' filter should be white instead of black

---

src/components/build-section/virtual-lab/me-model/BluePyEModelContainer.tsx

* Fixed wording EModel -> ME-model
* When the validation process is finished user is getting redirected directly to the analysis tab.

ME-model validation: fix wording, better redirect

---

src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(secondary)/build/me-model/new/configure/page.tsx
src/components/build-section/virtual-lab/me-model/BluePyEModelContainer.tsx

* Show spinner only on a button clicked by the user, and just disable the rest.
* Do not text wrap the me-model link.

Better me-model validation UX

---

src/hooks/session.ts

Due to [some optimisations](https://github.com/openbraininstitute/core-web-app/blob/develop/src/hooks/session.ts#L71) to avoid unnecessary re-renders on session change, in order to detect token refresh failures we should rely on the session directly from the next-auth lib, unlike it is currently implemented.
Addresses https://github.com/openbraininstitute/prod-build-emodel/issues/4.

Use current session to determine a state when refresh fails

---

src/components/LandingPage/LandingPage.module.css
src/components/LandingPage/LandingPage.tsx
src/components/LandingPage/constants.ts
src/components/LandingPage/layout/FooterPanel/FooterPanel.tsx
src/components/LandingPage/sections/sections.ts
src/components/LandingPage/styles.module.css
src/middleware.ts

OBI website added the financing page for the www.openbraininstitute.org/financing url

Added the page Financing

---

src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(pages)/library/page.tsx
src/components/explore-section/CardView/Card.tsx
src/entity-configuration/definitions/fields-defs/common.ts
src/entity-configuration/definitions/fields-defs/experimental.tsx
src/entity-configuration/definitions/fields-defs/model.tsx
src/entity-configuration/definitions/types.ts
src/features/listing-filter-panel/index.tsx
src/state/explore-section/list-view-atoms.ts

- entitycore will not support all the fields in the filter panel (after discussion with JDC), so we need a way to specify which legacy fields should continue to be supported and flag the others as not filterable, so we can enable them at any point of time when they are ready, 
- another field `isDisplayable` for allowing the user to `hide/show` specific fields in the table

extend filter panel options to display/hide columns

---

src/components/LandingPage/constants.ts
src/components/LandingPage/layout/FooterPanel/FooterPanel.tsx

simply renamed "financing" in the footer to "financing policy"

rename footer for financing policy

---

src/features/ephys-viewer/styles/ephys-plugin-styles.css

I hope there is a better way to reference global styles, will look into that a bit later.

Ephys viewer: correct reference to global styles

---

src/app/app/virtual-lab/(free)/explore/(interactive)/interactive/(data)/model/circuit/[id]/page.tsx
src/components/explore-section/Circuit/global/Columns.tsx
src/components/explore-section/ExploreListingLayout/index.tsx

* Use relative links so that when navigating to circuit details page in a context of vlab/project explore - we stay in the same context.
* Use `id` param instead of `key` for circuit details pages as the former one is what controls the presence of the menu.
* Hide brain region nav bar when opening circuit details - behaviour similar to the rest of entities.

Fix circuit layout

---

src/components/literature-suggestions/message-item/tools/articles/tool-articles/hooks.ts
src/components/literature-suggestions/message-item/tools/articles/tool-articles/types.ts

Literature search tool has a new output format now, but the current code was just silently ignoring it.
Since AI agent is going under heavy development, we may face many API breaks in the future.
Before this PR, if the format of the result of a tool was not as expected, the tool result was just silently ignored.
Now, we still ignore it, but we report a detailed error.

Articles cards do not appear anymore in the chat AI.

---

src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx
src/components/explore-section/Circuit/global/circuit-table.tsx
src/components/explore-section/Circuit/global/download/download-container.tsx
src/components/explore-section/Circuit/global/subcircuit-table.tsx
src/components/explore-section/Circuit/utils/circuits-match-filter.ts

- Reinstate search bar following the same logic as filter

Search bar for circuits

---

.deployment-envs/.env.staging
.env.development
src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(pages)/notebooks/NotebookTable.tsx
src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(pages)/notebooks/page.tsx
src/env.mjs

This PR adds a 'Run' button in the popup of the table of notebooks. The button is currently only added in the staging environment, it's only added to the list of OBI-managed notebooks (so not the notebooks owned by a user) and at the moment it doesn't do anything yet: it just shows a notification that a request to run a notebook was received.

Add button to run a notebook, for now only enabled in staging, and only for the regular (not uploaded by a user) notebooks

---

src/components/documentation/global/side-bloc.tsx
src/components/documentation/main/HeaderHome.tsx
src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx

- Added the title documentation to the side nav
- Change the welcome banner for "Get started with your Virtual Lab"

Refinement documentation 01

---

src/components/entities-type-stats/panel.tsx
src/features/entities/me-model/detail-view/card-viewers/emodel-overview-card.tsx
src/features/entities/me-model/detail-view/card-viewers/morphology-overview-card.tsx
src/page-wrappers/build/me-model/morphology.selection.tsx

This PR fixes some of the linting issues in core-web-app entitycore-migration: it's just renaming some variables.

Fix some linting issues by renaming variables

---

.github/workflows/publish-staging-next.yml

No longer push the entitycore-migration image tag: use either entitycore-migration-aws or entitycore-migration-azure

remove entitycore migration without suffix image tag

---

src/services/virtual-lab/build/me-model/bluepy-emodel.ts
src/services/virtual-lab/build/me-model/websocket.ts

This PR updates the logic to call ME-model validation service, according to changes introduced in [Integrate entitycore helper](https://github.com/openbraininstitute/me-model-analysis/pull/4).
Relates to [https://github.com/openbraininstitute/prod-singlecell-simulation/issues/126](https://github.com/openbraininstitute/prod-singlecell-simulation/issues/126).

Adapt ME-model validation calls to the new API (with entitycore support)

---

src/components/ai-assistant/ai-assistant.module.css

The header of the AI Assistant was wrapping and going outside of the container, when in collapsed mode.

Fix the heder title that was wrapping

---

src/components/explore-section/Circuit/global/download/download-item.module.css
src/components/explore-section/Circuit/global/download/download-item.tsx

Downloading directories is not yet possible on the platform. But the button was still here and clickable.
We replaced it with a "Coming soon..." label.

Preventing from downloading directories

---

src/features/small-microcircuit/_components/components.module.css
src/features/small-microcircuit/_components/section.tsx
src/features/small-microcircuit/index.tsx

When a header is selected, it appeared blue (with a gradient). Otherwise, it is white.
James wants this behavior only for the first two headers. The other, have (+) buttons to add extra properties.
He we wants them to stay white.
We also fixed a misalignment of the tooltips when the inputs have an error message displayed.

Remove blue highlight for headers with additional properties

---

src/features/ephys-viewer/atoms/index.ts
src/features/ephys-viewer/hooks/use-nwb-trace.ts

People might repeatedly switch to and from the NWB viewer from the circuit screen and now the second time it loads immediately.

Use atom with TTL to cache NWBs

---

src/features/ephys-viewer/components/trace-overview.tsx

Now it's using container queries so the layout adapts dynamically to the size of the container, instead of relying on window size/queries.

Better trace viewer layout

---

src/features/small-microcircuit/_components/atoms/index.ts
src/features/small-microcircuit/_components/utils.ts
src/features/small-microcircuit/index.tsx
src/features/small-microcircuit/types.ts
src/util/atoms.tsx

There were two issues with status updates:
1. Local changes (when status update arrives via streaming response) were not stored in atom, but rather in react state and were getting lost when navigating to other panel. Now status overrides (localStatus) is stored in the atom (with expiration) as well.
2. If the user leaves the page (or reloaded) there is no stream to update statuses. This is fixed by polling.
Now, it's a bit over-engineered. I think a good solution would be to split the sim request and the status update stream, so we can connect to it while the simulation running, but that will require additional changes - hopefully will do that after CNS.

Better persist status overrides, add status polling

---

src/app/app/v2/[virtualLabId]/[projectId]/explore/page.tsx
src/components/GenericErrorFallback/index.tsx
src/components/icons/buttons.tsx
src/components/tree/elements/helpers.ts
src/components/tree/index.tsx
src/features/brain-atlas-viewer/full-screen.tsx
src/features/brain-atlas-viewer/index.tsx
src/features/brain-region-hierarchy/context.tsx
src/features/brain-region-hierarchy/index.tsx
src/features/brain-region-hierarchy/region-banner.tsx
src/features/brain-region-hierarchy/species-switcher.tsx
src/ui/layouts/explore-layout.tsx
src/ui/segments/ai/container.tsx
src/ui/segments/explore/atlas.tsx
src/ui/segments/explore/entity-count.tsx
src/ui/segments/explore/header.tsx
src/ui/segments/explore/helpers.ts
src/ui/segments/explore/left-menu.tsx
src/ui/segments/workspaces/space-switcher/index.tsx
src/ui/use-query-keys/data.tsx
src/ui/use-query-keys/workspace.tsx

fix brain region tree scroll issue
fix layout for ai assistant expand

update add couters for entities

---

.github/workflows/run-audit.yml

@pgetta  or @bilalesi , would it be OK to merge this PR?
It basically adds an 'on demand' github action to store the output of pnpm audit in some build artifact. It doesn't affect the regular builds and it doesn't fail any builds if some security issue is found.

Add github action which runs pnpm audit and stores it as a build artifact

---

src/components/ai-assistant/message-item/tools-components/tools-components.tsx
src/components/ai-assistant/message-item/tools-components/tools/tool-thumbnail-generation-morphology-getone/tool-thumbnail-generation-morphology-getone.tsx
src/services/ai-agent/api/storage.ts

This tool do return images in the same exact way that tool `thumbnail-generation-morphology-getone` does:
1. The tool returns a file identifier.
2. We use it to ask `storage/${fileIdentifier}/presigned-url` backend entrypoint for the AWS bucket URL.
3. We fetch from the bucket and read the Response Header `X-Amz-Meta-Category` to get the mime type.

Added tool thumbnail-generation-electricalcellrecording-getone

---

src/ui/segments/project/balance.tsx
src/ui/segments/project/credits/credits-transfer-modal.tsx
src/ui/segments/virtual-lab-settings/elements/manage-credits.tsx
src/ui/segments/workflows/build/memodel/index.tsx

add wallet click on admin role

fix memodel configuration

---

src/features/entities/single-neuron-synaptome/build/phases/me-model-listing.tsx

It turns out the me-model selection during the synaptome build was broken.
@bilalesi I've fixed it, but not sure that's the correct way with the current changes.
This is being addressed in the scope of https://github.com/openbraininstitute/prod-platform-architecture/issues/140 but not really related to that ticket.

Fix me-model selection for synaptome build

---

src/components/ai-assistant/message-item/message-item.module.css
src/components/github-flavor-markdown/github-flavor-markdown.module.css

On Safari, long links were not wrapped and just overflowed.

Force long links in chat response to wrap
