openbraininstitute/core-web-app

README.md
https://teams.microsoft.com/l/message/19:goRm8vbHWjA-36Z085C6VM1Wzp7TIaAi-Vo81dqeyNc1@thread.tacv2/1737989041321?tenantId=c355c1d8-2b0b-4398-a8ea-b2134d2db027&groupId=30f83e22-b96e-4f60-9dde-e219a4d29a06&parentMessageId=1737989041321&teamName=Open%20Brain%20Institute&channelName=General&createdTime=1737989041321
=> update copyright text

src/api/notifications/index.tsx, src/app/page.tsx, src/components/Entrypoint/segments/AcceptInviteErrorDialog.tsx, src/components/Entrypoint/segments/Menu.tsx, src/components/Invites/index.tsx, src/components/Invites/utils.ts, src/components/LandingPage/Hero/Hero.tsx, src/components/LandingPage/LandingPage.tsx, src/components/LandingPage/Menu/PopupMenu/PopupMenu.tsx, src/components/LandingPage/buttons/LoginButton/LoginButton.tsx, src/components/VirtualLab/CreateVirtualLabButton/InformationForm.tsx, src/components/VirtualLab/CreateVirtualLabButton/MembersForm.tsx, src/components/VirtualLab/ProjectTeamTable/index.tsx, src/components/VirtualLab/VirtualLabDashboard/DashboardTotals.tsx, src/components/VirtualLab/VirtualLabHomePage/WelcomeUserBanner.tsx, src/components/VirtualLab/VirtualLabTeamTable/index.tsx, src/components/VirtualLab/projects/ModalInviteProjectMember/Footer.tsx, src/components/VirtualLab/projects/ModalInviteProjectMember/InviteProjectMember.tsx, src/components/VirtualLab/projects/ModalInviteProjectMember/InviteVlabMember.tsx, src/components/VirtualLab/projects/ModalInviteProjectMember/ModalInviteProjectMember.tsx, src/components/VirtualLab/projects/ModalInviteProjectMember/ModalInviteVlabMember.tsx, src/components/VirtualLab/projects/ModalInviteProjectMember/NewMember.tsx, src/components/VirtualLab/projects/VirtualLabProjectList/NewProjectModalForm.tsx, src/components/VirtualLab/projects/VirtualLabProjectList/index.tsx, src/types/virtual-lab/invites.ts, src/util/utils.ts
1. unify design of inviting members both in vlab, project
2. fix invitation processing messages and modal
=> update: unify styles for invites

src/middleware.ts
@pgetta please need another depoly after this, 
"i thought i saved the middleware file in the previous PR"
=> add privacy route to middleware

.deployment-envs/.env.production, .github/workflows/publish-production-image.yml
This is to merge current production hotfix into `develop` branch.
=> Update productin API domains

src/components/LandingPage/LandingPage.module.css, src/components/LandingPage/LandingPage.tsx, src/components/LandingPage/components/NewsPage/NewsPage.tsx, src/components/LandingPage/components/Video/Video.tsx, src/components/LandingPage/components/swipeable-cards-list/swipeable-cards-list.module.css, src/components/LandingPage/layout/FooterPanel/FooterPanel.module.css, src/components/LandingPage/layout/FooterPanel/FooterPanel.tsx, src/components/LandingPage/layout/Hero/NextPanel/NextPanel.module.css, src/components/LandingPage/styles.module.css, src/components/LandingPage/styles.ts, src/components/LandingPage/widgets/News/News.tsx, src/components/LandingPage/widgets/PortalsPanel/PortalsPanel.tsx, src/components/LandingPage/widgets/VirtualLabsPanel/card/card.tsx, src/components/LandingPage/widgets/repositories/hooks.groq, src/components/LandingPage/widgets/repositories/hooks.ts, src/components/LandingPage/widgets/repositories/repository-card/repository-card.module.css, src/components/LandingPage/widgets/repositories/repository-card/repository-card.tsx
* (11) "Browse all news" & "Our plans in details" look ugly on mobile 
* (2) The videos explore build experiment in mission and video next to portals appear as video on the whole screen when scrolling on the mobile 
* (3) White space on the right and no space on the left. 
* (5) The gray footer is too large on mobile
* (9) Inconsistent spacing.
* (21) resources button is not using sanity text
=> First round through the feesbacks

src/components/LandingPage/LandingPage.module.css, src/components/LandingPage/components/ProgressiveImage/ProgressiveImage.module.css, src/components/LandingPage/components/ProgressiveImage/ProgressiveImage.tsx, src/components/LandingPage/components/SanityContentRTF/SanityContentWidget/SanityContentWidget.tsx, src/components/LandingPage/components/Text/Text.module.css, src/components/LandingPage/components/Text/Text.tsx, src/components/LandingPage/content/milestones.groq, src/components/LandingPage/content/milestones.ts, src/components/LandingPage/layout/FooterPanel/FooterPanel.module.css, src/components/LandingPage/layout/FooterPanel/FooterPanel.tsx, src/components/LandingPage/sections/SectionContact/SectionContact.tsx, src/components/LandingPage/styles.module.css, src/components/LandingPage/widgets/ContributorsPanel/ContributorsList/ContributorsList.tsx, src/components/LandingPage/widgets/FromCellToBrain/FromCellToBrain.module.css, src/components/LandingPage/widgets/OurFoundations/OurFoundations.module.css, src/components/LandingPage/widgets/PortalsPanel/PortalsPanel.module.css, src/components/LandingPage/widgets/milestones/button/button.module.css, src/components/LandingPage/widgets/milestones/button/button.tsx, src/components/LandingPage/widgets/milestones/button/index.ts, src/components/LandingPage/widgets/milestones/index.ts, src/components/LandingPage/widgets/milestones/milestones.module.css, src/components/LandingPage/widgets/milestones/milestones.tsx, src/components/LandingPage/widgets/multiple-member/member/member.module.css, src/components/LandingPage/widgets/multiple-member/member/member.tsx, src/components/LandingPage/widgets/multiple-member/multiple-member.module.css, src/components/LandingPage/widgets/repositories/repositories.module.css, src/components/LandingPage/widgets/repositories/repositories.tsx, src/components/LandingPage/widgets/repositories/repository-card/repository-card.module.css
- (1) - [About] Center the portal column on large screen
- (2) - [All paragraphs p ] Add a 42px margin bottom
- (3) - [About] Increase the padding by 2.5em of the gray text in "our foundations"
- (4) - [About] Collaborators grid columns: (1) Mobile: 1; (2): Tablet portrait: 3; (3) Desktop: 4; (4) Super-desktop: 5
- (5) - [All pages] Add a 32px padding all hover the footer
- (6) - [Mission] name of the lab (subcellular, cellular, etc): Gabarito, weight 400, size 20-22px, word-spacing: 0.02em
- (7) - [Team] For member of the board and executive board have two lines (ellipsis) of biography and a button read more to expand
- (8) - [Home] Add new blocks Milestones slider
- (9) - [About] Profile card (Henry) should be left aligned.
- (10) - [Resources] Add a gray border {#D9D9D9) to each …
=> Fine tuning

src/components/LandingPage/sections/SectionContact/SectionContact.tsx
Removed the static Milestone section that appeared in the Contact page.
=> Fix contact page

package-lock.json, package.json, src/components/build-section/BrainRegionSelector/BrainRegions.tsx, src/components/explore-section/ExploreInteractive/DataTypeTabs.tsx, src/components/explore-section/ExploreInteractive/StatItem.tsx, src/components/explore-section/ExploreListingLayout/index.tsx, src/components/explore-section/Literature/user-journey/db.ts, src/components/explore-section/Literature/user-journey/index.ts
add indexdb store to save user interaction with brain region and artifacts and also the type of data
=> store user journey indexdb for literature

src/components/LandingPage/components/SanityContentRTF/SanityContentTitle/SanityContentTitle.tsx, src/components/LandingPage/components/SanityContentRTF/SanityContentTitle/special-widget.tsx, src/components/LandingPage/layout/Menu/Menu.tsx, src/components/LandingPage/styles.module.css
=> Add a big button to go to the coming-soon pge from the pricing

src/components/VirtualLab/create-entity-flows/checkout/contact-us.tsx, src/components/VirtualLab/create-entity-flows/checkout/payment-form.tsx, src/components/VirtualLab/create-entity-flows/checkout/price-card.tsx, src/components/VirtualLab/create-entity-flows/checkout/tiers-list.tsx, src/components/VirtualLab/create-entity-flows/profile/form.tsx, src/components/VirtualLab/create-entity-flows/project/overview.tsx, src/components/VirtualLab/create-entity-flows/project/vlabs-list.tsx, src/components/VirtualLab/create-entity-flows/subscription/billing-table.tsx, src/components/VirtualLab/create-entity-flows/subscription/elements.tsx, src/components/VirtualLab/create-entity-flows/subscription/history.tsx, src/components/VirtualLab/create-entity-flows/subscription/standalone-credits/buy-credits.tsx, src/components/VirtualLab/create-entity-flows/subscription/standalone-credits/credit-converter.tsx, src/components/VirtualLab/create-entity-flows/subscription/standalone-credits/payment-form.tsx, src/components/VirtualLab/create-entity-flows/virtual-lab/overview.tsx, src/components/VirtualLab/create-entity-flows/virtual-lab/verification-code.tsx
=> add test ids for testing

src/api/virtual-lab-svc/queries/types.ts, src/api/virtual-lab-svc/queries/virtual-lab.ts, src/app/app/virtual-lab/(home)/page.tsx, src/components/VirtualLab/labs-listing/listing.tsx, src/components/VirtualLab/side-bar/home-sidebar.tsx
Reverts openbraininstitute/core-web-app#135
=> Revert "Create multiple vlabs"

src/app/app/virtual-lab/(home)/page.tsx, src/components/LandingPage/components/Error/Error.module.css, src/components/LandingPage/components/SanityContentRTF/sanity-content-video/sanity-content-video.module.css, src/components/LandingPage/components/SanityContentRTF/sanity-content-video/sanity-content-video.tsx, src/components/LandingPage/components/Text/Text.tsx, src/components/LandingPage/components/Text/spacer/index.ts, src/components/LandingPage/components/Text/spacer/spacer.module.css, src/components/LandingPage/components/Text/spacer/spacer.tsx, src/components/LandingPage/components/Video/Video.tsx, src/components/LandingPage/content/types.ts
=> Add a spacer component and controls on video

src/components/LandingPage/components/Video/Video.module.css, src/components/LandingPage/components/Video/Video.tsx, src/components/LandingPage/widgets/VirtualLabsPanel/card/card.module.css, src/components/LandingPage/widgets/VirtualLabsPanel/card/card.tsx, src/services/sanity/sanity.ts
=> Fix video of virtual labs with height zero

.deployment-envs/.env.production, .deployment-envs/.env.staging, .env.development, package-lock.json, package.json, src/components/LandingPage/components/select-currency/select-currency.tsx, src/components/LandingPage/content/pricing.groq, src/components/LandingPage/content/pricing.ts, src/components/LandingPage/widgets/PriceList/contact-us/contact-us.module.css, src/components/LandingPage/widgets/PriceList/contact-us/contact-us.tsx, src/components/LandingPage/widgets/PriceList/contact-us/index.ts, src/components/LandingPage/widgets/PriceList/large-screen/PlanHeader/PlanHeader.tsx, src/components/LandingPage/widgets/PriceList/small-screen/plan-header/plan-header.tsx, src/components/litterature-suggestions/hooks.ts, src/services/sanity/sanity.ts
We removed the "currency" label before the combo box.
And we added a "Contact Us" button for the Premium Plan.
=> Remove currency label

src/components/Buttons/ShowcasesSideNav.tsx, src/components/PublicProjects/sections/Description.tsx, src/components/icons/HomeFillIcon.tsx, src/components/icons/index.ts
Added a home button inside the single showcase page
=> Added a home button to single showcase pages

src/components/literature-suggestions/error/error.module.css, src/components/literature-suggestions/error/error.tsx, src/components/literature-suggestions/error/index.ts, src/components/literature-suggestions/literature-suggestions.module.css, src/components/literature-suggestions/literature-suggestions.tsx, src/components/literature-suggestions/message-item/message-item.module.css, src/components/literature-suggestions/message-item/message-item.tsx, src/components/literature-suggestions/spinner/spinner.module.css, src/components/literature-suggestions/spinner/spinner.tsx, src/components/literature-suggestions/suggested-questions/hardcoded-suggestions/suggestions-list.ts, src/services/ai-agent/hooks/chat.ts
* Preventing the user to ask another question if the previous one is still pending.
* Display an understandable error message when the user has exceeded their rate limit.
=> Display userfriendly eror when the rate has been exceeded.

src/components/Invites/index.tsx, src/components/VirtualLab/create-entity-flows/checkout/index.tsx, src/components/VirtualLab/create-entity-flows/checkout/payment-form.tsx
Few things:
* switched to use subscription instead of user session (as the session is not automatically update - will fix that later)
* subscription screen is pretty busy, so I've moved the message about pro subscription requirement to the invite page itself.
=> Fix invite redirects and non-pro subscription status

.gitignore, package-lock.json, src/components/literature-suggestions/error/error.tsx, src/components/literature-suggestions/literature-suggestions.module.css, src/components/literature-suggestions/message-item/message-item.module.css
=> Insufficent funds error and user question background

src/components/Invites/index.tsx
=> Fix styles in invite page

src/components/PublicProjects/MEModels/MEModelTable.tsx, src/components/PublicProjects/PublicProjectMain.tsx, src/components/PublicProjects/SinglePublicProjectCard.tsx, src/components/PublicProjects/api/fetchSingleCase.ts, src/components/PublicProjects/sections/Description.tsx, src/components/PublicProjects/type/index.ts, src/components/terms-of-use-acceptance/index.ts
- Added condition if project doesn't have any videos
- Removed column of morphology ID and trace ID as they are mostly unaccessible anymore since the end of BBP
- Fixed some styling issues
=> Public project adjustment 1

src/app/app/virtual-lab/(free)/explore/(interactive)/interactive/(data)/model/[modelType]/[id]/page.tsx, src/components/explore-section/Synaptome/DetailView/index.tsx
As there is no vlab/project context and the link doesn't work with such conditions.
FYI, @ayimaok
=> Do not show simulate button in Explore - synaptome model details

src/components/literature-suggestions/suggested-questions/hardcoded-suggestions/hardcoded-suggestions.ts, src/components/literature-suggestions/suggested-questions/hardcoded-suggestions/suggestions-list.ts
This PR relates to this issue: https://github.com/openbraininstitute/prod-explore-functionality/issues/72
=> Hardcoded questions for when the user is on the top of the brain hierarchy

src/components/literature-suggestions/suggested-questions/hardcoded-suggestions/hardcoded-suggestions.ts, src/components/literature-suggestions/suggested-questions/hardcoded-suggestions/snapshot.ts
We now use the region ID to know if we are at the top of the hierarchy.
=> Use the region ID to know if it's the root

src/components/explore-section/common/pdf/PDFViewer.tsx, src/components/literature-suggestions/literature-suggestions.module.css, src/components/literature-suggestions/literature-suggestions.tsx
=> Message that states that the AI is only suited for literature search

src/components/VirtualLab/create-entity-flows/common/user.tsx, src/components/user-menu/index.tsx
after Daniel changes in KC, the first/last names are optional, so in the user menu; will display the full name if exists and fallback to username
=> use full name in the user side menu and fallback to username

src/app/app/virtual-lab/(free)/explore/layout.module.css, src/components/explore-section/ControlPanel/index.tsx
=> Prevent Filter panel from hidding the AI panel

src/app/app/virtual-lab/(free)/explore/layout.module.css, src/app/app/virtual-lab/lab/[virtualLabId]/(lab)/overview/page.tsx, src/components/VirtualLab/DiscoverObpPanel/index.tsx
Related to this issue: https://github.com/openbraininstitute/prod-obi-site/issues/135
Now we have this:
=> Remove label with BBOP mentioned

src/app/app/virtual-lab/lab/[virtualLabId]/(lab)/overview/page.tsx, src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/simulate/layout.tsx, src/components/LabTabs/index.tsx, src/components/VirtualLab/DiscoverObpPanel/index.tsx, src/components/VirtualLab/ScopeSelector/index.tsx, src/components/VirtualLab/projects/VirtualLabProjectSidebar/index.tsx
This relates to ticket https://github.com/openbraininstitute/prod-obi-site/issues/136
=> Replace Simulate with Experiment

src/components/explore-section/ExploreListingLayout/index.tsx
Fixes https://github.com/openbraininstitute/prod-explore-functionality/issues/88#issuecomment-2778404295
Also now the circuit menu is shown only in model data.
=> Fix menu flickering, show circuits only in models section

src/components/explore-section/ExploreListingLayout/index.tsx
Addresses https://github.com/openbraininstitute/prod-explore-functionality/issues/89#issuecomment-2786266974
=> Make explore list span available space instead of full window height

.github/workflows/publish-staging-image.yml, src/components/VirtualLab/ScopeSelector/index.tsx
1. disable auto-deploy for staging
2. change ion to coming soon
=> change ion to coming soon/disable autodeploy staging gh

src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/build/page.tsx, src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/simulate/page.tsx, src/hooks/virtual-labs/infinite-scroll.tsx
1. fix fixed buttons in simulate page
2. fix loading in simulate listing table
=> fix fixed btns in simulate page

src/components/VirtualLab/item/project-item.tsx
Correction of text for label of project creation.
Concerned ticket: https://github.com/orgs/openbraininstitute/projects/10/views/21?filterQuery=assignee%3A%40me&pane=issue&itemId=106714694&issue=openbraininstitute%7Cprod-obi-website%7C207
=> Corrected the apostrophe s for project creation

src/components/PublicProjects/MEModels/MEModelTable.tsx, src/components/PublicProjects/sections/Artifacts.tsx
Fixed the error with reading length of null
https://github.com/openbraininstitute/prod-obi-site/issues/183
=> Public project: fixed error (ticket #183)

src/components/VirtualLab/side-bar/home-sidebar.tsx
=> Added a -s to public project

src/components/MorphoViewer/Settings/ColorsLegend/ColorInput/ColorInput.tsx
Relates to https://github.com/openbraininstitute/prod-explore-functionality/issues/101#event-17391821227
FYI, @tolokoban
=> Morph viewer: correct setting opacity to control neurite visibility

package-lock.json, src/components/explore-section/Circuit/global/Columns.tsx, src/components/explore-section/Circuit/utils/filter-circuits.ts
There was few linting errors in the AntD Resizable Columns.
=> Fix all lint issues

src/api/apiClient.ts, src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(pages)/library/page.tsx, src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/build/page.tsx, src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/simulate/page.tsx, src/entity-configuration/definitions/view-defs/experimental.ts, src/entity-configuration/definitions/view-defs/index.tsx, src/entity-configuration/definitions/view-defs/model.ts, src/entity-configuration/domain/experimental/bouton-density.ts, src/entity-configuration/domain/experimental/electrical-cell-recording.ts, src/entity-configuration/domain/experimental/neuron-density.ts, src/entity-configuration/domain/experimental/reconstruction-morphology.ts, src/entity-configuration/domain/experimental/synapse-per-connection.ts, src/entity-configuration/domain/helpers.ts, src/entity-configuration/domain/model/e-model.ts, src/entity-configuration/domain/model/me-model.ts, src/entity-configuration/domain/model/single-neuron-synaptome.ts, src/entity-configuration/domain/types.ts, src/features/bookmark/control.tsx, src/features/bookmark/footer.tsx, src/features/bookmark/helpers.ts, src/features/bookmark/listing-table.tsx, src/features/bookmark/tabs.tsx, src/features/bookmark/view.tsx, src/features/details-view/header.tsx, src/hooks/useHorizontalScrollInfo.tsx, src/i18n/en/bookmark.ts, src/util/common.ts, src/utils/url-builder.ts
refactor bookmarking and use entity new type
=> add bookmark to build screen

src/components/PublicProjects/HeaderPublicProject.tsx, src/components/PublicProjects/NavigationSections.tsx, src/components/PublicProjects/PublicProjectMain.tsx, src/components/PublicProjects/type/index.ts, src/components/explore-section/Circuit/DetailView/MainDetailViewCore.tsx, src/types/public-projects/index.ts
- Changed the way the url catch the searchParams to maintain correctly the last section visited
=> Get the searchParams when changing route to a new URL

src/components/Invites/index.tsx
issue: https://github.com/openbraininstitute/prod-virtual-lab/issues/15
=> allow user to accept invites without active paid subscription

src/api/entitycore/types/index.ts, src/state/morpho-viewer/index.ts
Relates to https://github.com/openbraininstitute/prod-platform-architecture/issues/23
=> Switch morphoviewer to entitycore assets

lefthook.yml, package-lock.json, package.json
this is a simple commit hooks to use for the moment to be able to detect issues before committing or pushing new PRs
=> add commit hooks using lefthook

src/components/explore-section/Circuit/DetailView/global/ParameterBox.tsx, src/components/explore-section/Circuit/DetailView/header/CircuitMetadata.tsx, src/components/explore-section/Circuit/DetailView/header/CircuitParameters.tsx, src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx
- Added link to parent circuit parameter box
- Added link to the license parameter box
=> Circuit detail active link licence parent circuit

src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx, src/components/explore-section/Circuit/global/Columns.tsx, src/components/explore-section/Circuit/type/index.tsx
- Added type to the Circuit schema
- Added the column to the table
=> Circuit table add published in column

src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx, src/components/explore-section/Circuit/global/Columns.tsx, src/components/explore-section/Circuit/global/ViewToggle.tsx, src/components/explore-section/Circuit/global/circuit-table.tsx, src/components/explore-section/Circuit/global/numeric-filter.tsx, src/components/explore-section/Circuit/utils/flatten-circuits.ts, src/components/icons/FlatListViewIcon.tsx, src/components/icons/HierarchicalViewIcon.tsx, src/components/icons/index.ts
Adding the logic of showing table either hierarchically or flatten.
=> Circuit table hierarchical and flat list views

src/components/explore-section/Circuit/DetailView/header/CircuitParameters.tsx, src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx, src/components/explore-section/Circuit/global/Columns.tsx, src/components/explore-section/Circuit/utils/format-number-with-comma.ts
- Created a function to format number with comma every 3 digit
- Added this function to detail view # neurons, # connections, # synapses
- Added this function to table view
=> Circuits format number with comma

src/components/TreeNavItem/index.tsx, src/components/build-section/BrainRegionSelector/BrainRegions.tsx, src/components/literature-suggestions/literature-suggestions.tsx, src/components/literature-suggestions/suggested-questions/suggested-questions.tsx
Fix: 
https://github.com/openbraininstitute/prod-explore-functionality/issues/148
=> Section not set

src/components/explore-section/Circuit/DetailView/global/ParameterBox.tsx, src/components/explore-section/Circuit/DetailView/header/circuit-metadata.tsx, src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx
Created a modal for metadata with long list such as contributors or institutions
=> Handle view all for contributors and institutions

src/components/explore-section/Literature/user-journey/index.ts, src/components/literature-suggestions/literature-suggestions.module.css, src/components/literature-suggestions/suggested-questions/hardcoded-suggestions/suggestions-list.ts
And fix a bug in a hardcoded suggestions.
The related ticket is: https://github.com/openbraininstitute/prod-explore-functionality/issues/110#issuecomment-2886075425
=> Reduce the journey size from 10 to 3

src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(pages)/library/page.tsx, src/features/bookmark/view.tsx
small fix for the library, another PR for updating the tab when no data available for a specific entity type
=> fix libarary view

src/features/bookmark/tabs.tsx, src/features/bookmark/view.tsx, src/features/entities/single-neuron-synaptome/build/elements/synapse-config-form.tsx, src/features/entities/single-neuron-synaptome/build/elements/synapse-set.tsx, src/i18n/en/synaptome.ts, src/state/explore-section/list-view-atoms.ts, src/util/explore-section/listing-selectors.ts
handling synaptome config asset failing error as early as possible
=> fix synaptome model creation error

src/components/PublicProjects/SingleNotebook.tsx, src/components/PublicProjects/sections/Artifacts.tsx, src/components/PublicProjects/sections/Notebook.tsx, src/components/PublicProjects/style/notebook.module.css, src/components/PublicProjects/tables/columns/e-model-columns.tsx, src/components/PublicProjects/tables/columns/me-model-columns.tsx, src/components/PublicProjects/tables/e-model-table.tsx, src/components/PublicProjects/tables/me-model-table.tsx, src/components/PublicProjects/tables/synaptome-model-table.tsx, src/components/PublicProjects/type/artifactsType.ts, src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx, tailwind.config.js
Correction based on ticket #110 https://github.com/openbraininstitute/prod-obi-website/issues/110
=> Public projects corrections ayima feedback

src/components/VirtualLab/side-bar/control.tsx, src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx
In response to https://github.com/orgs/openbraininstitute/projects/10/views/3?sliceBy%5Bvalue%5D=loris-olivier-obi&pane=issue&itemId=112539198&issue=openbraininstitute%7Cprod-virtual-lab%7C45
=> Global side button home button

.github/workflows/publish-staging-next-azure.yml, .github/workflows/publish-staging-next.yml
Create the image for the deployment in Azure in a separate GitHub action, which has to be triggered manually for now
=> Create the image for the deployment in Azure in a separate GitHub action, which has to be triggered manually for now

src/components/VirtualLab/ScopeSelector/index.tsx, src/constants/virtual-labs/sidemenu.ts
=> Fix the names in the nav bar

src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(pages)/notebooks/NotebookTable.tsx
replace entitycore by main to fetch the notebook.
=> Notebook entitycore

src/components/zoomable-image/index.ts, src/components/zoomable-image/zoomable-image.module.css, src/components/zoomable-image/zoomable-image.tsx, src/features/small-microcircuit/_components/circuit-preview/circuit-preview.module.css, src/features/small-microcircuit/_components/circuit-preview/circuit-preview.tsx, src/features/small-microcircuit/index.tsx, src/features/small-microcircuit/small-microcircuit.module.css
The button was gone after the removal of the circuit name
=> Restore the CopyCampaign ID button

src/components/VirtualLab/ScopeSelector/index.tsx, src/components/VirtualLab/ScopeSelector/styles.module.css, src/components/VirtualLab/ScopeSelector/tiles.ts
=> Fixed the scale with 4 columns

src/components/VerticalLinks/index.tsx, src/constants/virtual-labs/sidemenu.ts
This was due to the fact that we renamed `simulate` into `experiment` and a bug appeared.
=> Experiment section in the navigation menu was not highlighted

src/api/entitycore/queries/assets/index.ts, src/api/entitycore/types/shared/global.ts, src/features/small-microcircuit/_components/atoms/index.ts, src/features/small-microcircuit/_components/file-viewer/index.tsx, src/features/small-microcircuit/_components/simulation-files/index.tsx, src/features/small-microcircuit/_components/simulation-status/index.tsx, src/features/small-microcircuit/index.tsx, src/services/small-scale-simulator/circuit.ts
=> Add circuit simulaiton input/output files

src/features/ephys-viewer/components/trace-details-view.tsx, src/features/ephys-viewer/components/trace-overview.tsx, src/features/ephys-viewer/ephys-viewer.tsx, src/features/ephys-viewer/nwb-trace.ts, src/features/small-microcircuit/_components/file-viewer/index.tsx
This implement a better layout for small circuit simulation voltage recordings where there are multiple cells each having only one repetition/sweep.
Now such traces are shown next to each other in a single grid.
=> Single rec multi cell trace viewer layout

src/components/LandingPage/components/ProgressiveImage/ProgressiveImage.tsx
```
4 | import { classNames } from '@/util/utils';
5 |
> 6 | import { classNames } from '@/util/utils';
|          ^^^^^^^^^^
7 |
8 | import styles from './ProgressiveImage.module.css';
9 |
```
=> Fix merge issue

src/components/VirtualLab/ScopeSelector/index.module.css, src/components/ai-assistant/suggested-questions/hardcoded-suggestions/hardcoded-suggestions.ts, src/components/ai-assistant/suggested-questions/hardcoded-suggestions/snapshot.ts, src/services/ai-agent/api/suggestion.ts, src/services/ai-agent/hooks/suggestion.ts
We were using an old way (pre-entitycore) to check if a region is the root region.
=> Fix suggestions for root brain region

src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx, src/entity-configuration/definitions/fields-defs/common.tsx, src/entity-configuration/definitions/renderer.tsx, src/entity-configuration/definitions/types.ts, src/features/details-view/overview.tsx, src/features/small-microcircuit/_components/utils.ts
- Put the metadata on a 4 grid cols
- Put the description on 4 columns and contributors + registration date each on 2 columns
- Added a renderForDetailView for specific modal-related behavior to common.tsx
- Added a modal if contributors are more than 6
=> 204 e model UI needs improvments

src/components/VirtualLab/projects/VirtualLabProjectAdmin/ProjectJobReportList.tsx, src/types/accounting/index.ts
Relates to https://github.com/openbraininstitute/prod-circuit-simulation/issues/51.
=> Add accounting types and labels for small circuit simulations

src/api/entitycore/queries/model/circuit.ts, src/state/explore-section/list-view-atoms.ts
this allowed by JDC to have the fix in prod
=> version 17-07-02

src/components/MorphoViewer/Settings/Settings.tsx, src/components/MorphoViewer/hooks/settings.ts
Reverts openbraininstitute/core-web-app#668
=> Revert "Remove Morphoviewer settings persistance"

src/components/documentation/tutorials/single-tutorial-content.tsx, src/components/explore-section/Circuit/DetailView/main-detail-view-core.tsx
Now time stamps are displayed if they have been defined in Sanity
=> Fix timestamps in tutorials

package.json, pnpm-lock.yaml, src/app/app/providers.tsx, src/query-provider/client.tsx, src/query-provider/examples.md, src/query-provider/query-client.tsx, src/query-provider/server.tsx, src/utils/url-builder.ts
- **client-side fetching**: simplifies dynamic data fetching with `useQuery`, enabling real-time updates and granular loading states for better UX, mutation (`useMutation`), invalidation, caching, infinite query (`useInifiniteQuery`) ...
- **unified data management**: reducing redundant API calls and ensuring consistency across routes.
- **DX (developer experience)**: declarative api and TS support streamline data-fetching logic, a real boost productivity and maintainability.
- **Server prefetching**:  it can be used to prefetch data in the server and hydrated in the client, if some functionalities needed from tanstack-query, else it's preferable to use server component
=> feat: add react query 

package.json, pnpm-lock.yaml, src/app/app/v2/[virtualLabId]/[projectId]/notebooks/layout.tsx, src/app/app/v2/[virtualLabId]/[projectId]/notebooks/page.tsx, src/components/FilterControls/FilterControls.tsx, src/components/VirtualLab/Search/index.tsx, src/features/small-microcircuit/index.tsx, src/ui/hooks/use-search.tsx, src/ui/layouts/notebook-inner-layout.tsx, src/ui/layouts/notebooks-layout.tsx, src/ui/segments/notebooks/header.tsx, src/ui/segments/notebooks/left-nav-menu.tsx, src/ui/segments/notebooks/table/ActionPopover.tsx, src/ui/segments/notebooks/table/action-menu.tsx, src/ui/segments/notebooks/table/columns.tsx, src/ui/segments/notebooks/table/content-modal.tsx, src/ui/segments/notebooks/table/filter-section.tsx, src/ui/segments/notebooks/table/index.tsx, src/ui/segments/notebooks/table/notebook-tabs.tsx, src/ui/segments/notebooks/table/table-columns.tsx, src/ui/segments/notebooks/table/table-styles.tsx, src/ui/segments/notebooks/table/use-notebook-table.ts, src/ui/segments/notebooks/table/utils.ts, src/utils/get-sorter.ts
- Migrated what Gil has done into the new UX
=> Notebook part 1

src/components/ai-assistant/prompt/tools-selector/tools-selector.module.css
Import AI tools selector into the new UI.
=> Fix misalignement of the tools selector

src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(pages)/notebooks/member/UserNotebookPage.tsx, src/app/app/virtual-lab/lab/[virtualLabId]/project/[projectId]/(pages)/notebooks/member/page.tsx, src/util/virtual-lab/fetchNotebooks.ts
- If a notebook fails to load still display the rest of the notebooks.
=> Hotfix notebook

src/api/virtual-lab-svc/queries/types.ts, src/api/virtual-lab-svc/queries/user.ts, src/api/virtual-lab-svc/queries/virtual-lab.ts, src/app/api/sync/boot/route.ts, src/app/app/v2/sync/page.tsx, src/ui/segments/app-setup/helpers.tsx, src/ui/segments/app-setup/workspace-customization.tsx, src/ui/segments/app-setup/workspace-identity.tsx, src/ui/segments/app-setup/workspace-provision.tsx, src/ui/segments/project/create/form.tsx, src/ui/segments/project/preview/index.tsx
- fix some validation behaviors for forms
- add setting last used workspace endpoint and logic
**NOTE**: the commented mutations are waiting for another PR in the vlab-svc to update the recent workspace
I will create another PR to uncomment those when we have the other merged
=> improve onboarding workflow

src/app/app/v2/[virtualLabId]/[projectId]/(home)/credits/page.tsx, src/entity-configuration/definitions/renderer.tsx, src/entity-configuration/definitions/view-defs/experiment.ts, src/ui/segments/mini-detail-view/index.tsx, src/ui/segments/mini-detail-view/previews/single-neuron-simulation-preview.tsx, src/ui/segments/project/left-nav-menu.tsx, src/ui/segments/workspaces/space-switcher/item.tsx
add mini-details-view  for simulation
=> virtual lab menu item should open the settings

src/api/entitycore/types/entities/single-neuron-synaptome.ts, src/api/entitycore/types/extended-entity-type.ts, src/app/api/sync/boot/route.ts, src/entity-configuration/definitions/renderer.tsx, src/features/entities/neuron-simulation/experiment/visualization/plot-renderer.tsx, src/features/views/listing/browse-entity.tsx, src/state/simulate/single-neuron.ts, src/ui/molecules/tooltip/index.tsx, src/ui/segments/app-setup/workspace-customization.tsx, src/ui/segments/data-table/elements/controls.tsx, src/ui/segments/data-table/index.tsx, src/ui/segments/data-table/table.tsx, src/ui/segments/explore/header.tsx, src/ui/segments/mini-detail-view/index.tsx, src/ui/segments/project/balance.tsx, src/ui/segments/workflows/build/memodel/e-model.tsx, src/ui/segments/workflows/build/memodel/m-model.tsx, src/ui/segments/workflows/build/memodel/menu.tsx, src/ui/segments/workflows/build/single-neuron-synaptome/me-model.tsx, src/ui/segments/workflows/build/single-neuron-synaptome/menu.tsx, src/ui/segments/workflows/build/single-neuron-synaptome/synapse-set-item.tsx, src/ui/segments/workflows/build/single-neuron-synaptome/synapse-set-menu-item.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/amperage-configuration.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/elements/menu.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/elements/results-menu.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/runner.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/steps/recording-locations.tsx, src/ui/segments/workflows/simulate/single-neuron/single-neuron-synaptome/item/frequency-input.tsx, src/ui/segments/workflows/simulate/single-neuron/single-neuron-synaptome/item/item.tsx
- fix license
- fix download button in me-model selection (synaptome build)
- fix tooltip arrows
- disable bookmark for the moment
=> fix synaptome build

src/hooks/useExploreColumns.tsx, src/ui/segments/data-table/elements/use-data-table-columns.tsx
Same as but for v2: https://github.com/openbraininstitute/core-web-app/pull/832/files
=> Fix unit v2

package.json, pnpm-lock.yaml, src/components/ai-assistant/prompt/prompt.tsx, src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/brain-atlas-viewer-gltf.module.css, src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/brain-atlas-viewer-gltf.tsx, src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/camera.ts, src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/hooks.ts, src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/index.ts, src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/painter.ts, src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/services/services.ts, src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/types.ts, src/features/brain-atlas-viewer/index.tsx, src/features/brain-atlas-viewer/temporary-switcher/index.ts, src/features/brain-atlas-viewer/temporary-switcher/temporary-switcher.module.css, src/features/brain-atlas-viewer/temporary-switcher/temporary-switcher.tsx, src/ui/use-query-keys/atlas.ts
The old viewer was rendering this:
=> Using GLB for meshes and new painter for point clouds

src/components/ai-assistant/message-item/message-item.module.css, src/components/ai-assistant/message-item/message-item.tsx, src/components/ai-assistant/panel-content/history/history.tsx
=> Fix delete thread

src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/brain-atlas-viewer-gltf.module.css, src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/services/services.ts
A more detailed error can be found in the console.
=> Report errors in region mesh fetching

src/ui/hooks/use-disable-workspace-modal-full-height.tsx, src/ui/segments/project/preview/index.tsx, src/ui/segments/project/team/team.tsx, src/ui/segments/virtual-lab-settings/sections/team.tsx, src/ui/segments/workflows/elements/browse-header.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/elements/menu.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/steps/experiment-setup.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/steps/overview.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/steps/recording-locations.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/steps/result.tsx, src/ui/segments/workflows/simulate/single-neuron/shared/steps/stimulation-protocol.tsx, src/ui/segments/workspaces/space-manager/index.tsx, src/ui/segments/workspaces/space-switcher/item.tsx, src/utils/browser.ts
fix workspace modal height in safari
=> fix allow action to cancel invitation for member user

src/app/app/virtual-lab/[virtualLabId]/[projectId]/data/(browse)/browse/entity/[type]/page.tsx, src/app/app/virtual-lab/[virtualLabId]/[projectId]/data/view/[type]/[id]/layout.tsx, src/ui/segments/explore/helpers.ts
As per: 
https://teams.microsoft.com/l/message/19:bd6bc3be6d154dd5aebc401d0d7e3845@thread.tacv2/1759220827282?tenantId=c355c1d8-2b0b-4398-a8ea-b2134d2db027&groupId=30f83e22-b96e-4f60-9dde-e219a4d29a06&parentMessageId=1759132787282&teamName=Open%20Brain%20Institute&channelName=Staging%20to%20Production&createdTime=1759220827282
=> Temporarily hide ion channel model

src/features/brain-atlas-viewer/brain-atlas-viewer-gltf/painter.tsx, src/ui/segments/project/preview/index.tsx
=> fix notification for point cloud when av is -1

src/ui/segments/ai/container.tsx, src/ui/segments/project/banner/banner.tsx, src/ui/segments/workspaces/top-menu-nav.tsx
fix top menu double click
add remaining characters in project renaming
=> fix ai panel animation

src/components/LandingPage/constants.ts, src/components/LandingPage/sections/sections.ts, src/middleware.ts
this is gonna go to staging then to prod, as requested by @jdcourcol
=> added SFN 2025 section (#923)
